### Variables d'environnement
@baseUrl = http://localhost:3333/api/v1
@email = test@example.com
@password = password123
### 3. Extraire le token de la réponse précédente
@token = oat_Mg.WjVHOFRQQUt2R2xIZjVDUHJ1MkwxUFJabndwc0xsbTN1aTFGRmpEZTIzOTExMjQxNjg

### 1. Inscription
POST {{baseUrl}}/auth/register
Content-Type: application/json

{
  "firstName": "Test",
  "lastName": "User",
  "email": "{{email}}",
  "phone": "+33123456789",
  "birthDate": "1990-01-01",
  "password": "{{password}}",
  "passwordConfirmation": "{{password}}"
}

### 2. Connexion
# @name login
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
  "email": "{{email}}",
  "password": "{{password}}"
}

### 3. Réinitialisation de mot de passe
POST {{baseUrl}}/auth/forgot-password
Content-Type: application/json

{
  "email": "{{email}}"
}

### 4. Réinitialisation de mot de passe
POST {{baseUrl}}/auth/reset-password
Content-Type: application/json

{
  "email": "{{email}}"
}
### 5. Profil utilisateur
GET {{baseUrl}}/auth/current-user
Authorization: Bearer {{token}}

### 6. Déconnexion
POST {{baseUrl}}/auth/logout
Authorization: Bearer {{token}}

### 7. Renvoyer un email de vérification
POST {{baseUrl}}/auth/resend-email
Content-Type: application/json

{
  "email": "{{email}}"
}
