### Variables d'environnement
@baseUrl = http://localhost:3333/api/v1
@token = oat_MQ.ZV9OTmc3d2twSXItRGdlc3dfMkVGZjZEYU9yWkdYdmtOTmEzRGczeTM1NTgyMjY4OTM

### 1. Création d'un véhicule
POST {{baseUrl}}/vehicles
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "brand": "Toyota",
  "model": "Camry",
  "color": "Black",
  "licensePlate": "BO-123-AB",
  "year": 2022,
  "numberOfSeats": 5,
  "fuelType": "Gasoline",
  "hasAirConditioning": true,
  "isVerified": true
}

### 2. Récupération de tous les véhicules
GET {{baseUrl}}/vehicles
Content-Type: application/json
Authorization: Bearer {{token}}

### 3. Récupération d'un véhicule spécifique
GET {{baseUrl}}/vehicles/9b9ed03c-17b3-4391-9c35-b334affcffd5
Content-Type: application/json
Authorization: Bearer {{token}}

### 4. Mise à jour d'un véhicule
PUT {{baseUrl}}/vehicles/9b9ed03c-17b3-4391-9c35-b334affcffd5
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "brand": "Tesla",
  "model": "Model S",
  "color": "Black",
  "licensePlate": "ABC1234",
  "year": 2025,
  "numberOfSeats": 5,
  "fuelType": "Electric",
  "hasAirConditioning": true,
  "isVerified": true
}

### 5. Suppression d'un véhicule
DELETE {{baseUrl}}/vehicles/9b9ed03c-17b3-4391-9c35-b334affcffd5
Content-Type: application/json
Authorization: Bearer {{token}}

### 6. Récupération de tous les véhicules par l'id du conducteur
GET {{baseUrl}}/vehicles/driver/3
Content-Type: application/json
Authorization: Bearer {{token}}
